name: Deploy to 
on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        run: npm install

        # - name: Lint
        # run: npm run lint

      - name: Build
        run: npm run build

      - name: Deploy
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.S3_GITHUB_DEPLOY_ACCESS_ID }}  # Ensure this secret is correctly set
            AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_GITHUB_DEPLOY_SECRET_KEY }}  # Ensure this secret is correctly set
          run: |
        run: |
          aws s3 cp  aws s3 cp --recursive --region ${{ secrets.AWS_REGION }} dist s3://aws-project-utiva
          
            
            
